# See https://wiki.hypr.land/Configuring/Keywords/
$mainMod = SUPER # Sets "Windows" key as main modifier
$screenshot = grim -g "$(slurp)" - | tee ~/Pictures/Screenshots/shot-$(date +%Y%m%d-%H%M%S).png | wl-copy
$volRaise = wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+ && swayosd-client --output-volume raise 
$volLower = wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- && swayosd-client --output-volume lower 
$brightRaise = brightnessctl -e4 -n2 set 5%+ && swayosd-client --brightness raise
$brightLower = brightnessctl -e4 -n2 set 5%- && swayosd-client --brightness lower
