# ===============================
#   Hyprlock – Minimal + Clock
# ===============================

# ---------- BACKGROUND ----------
background {
#    path = /home/marcy/Pictures/wpp/018.gif
    path = screenshot
    blur = true
    blur_size = 5
    blur_passes = 1
    color = rgba(0,0,0,0.75)
}

# ---------- CLOCK (24h) ----------
label {
    monitor =
    text = $TIME
    font_size = 45
    #color = rgba(255,255,255,0.75)

    position = 0, 80
    halign = center
    valign = center

    shadow_passes = 2
    shadow_size = 4
}

# ---------- PASSWORD FIELD ----------
input-field {
    monitor =
    size = 300, 50
    rounding = 8

    outline_thickness = 2
    outline_color = rgba(255,255,255,0.2)

    inner_color = rgba(0,0,0,0.4)
    font_color = rgba(255,255,255,1.0)

    placeholder_text = Password
    fail_text = Wrong password

    position = 0, 0
    halign = center
    valign = center
}

