# Example binds, see https://wiki.hypr.land/Configuring/Binds/ for more
bind = $mainMod, T, exec, $terminal
#bind = SUPER, O, exec, hyprctl dispatch setopacity,
bind = $mainMod, W, killactive,
bind = $mainMod, K, killactive, # Default
bind = $mainMod, M, exit,
bind = $mainMod, F, exec, $fileManager
bind = $mainMod, G, exec, $chatGpt
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, $menu # Default
bind = $mainMod SHIFT, Z, exec, $menu
bind = $mainMod, L, exec, $lock
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, J, togglesplit, # dwindle
bind = $mainMod SHIFT, S, exec, $screenshot
bind = $mainMod SHIFT, TAB, fullscreen,
bind = $mainMod CTRL, TAB, fullscreenstate, 0 2
