# Ref https://wiki.hypr.land/Configuring/Workspace-Rules/
# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
# windowrulev2 = floating:1, class:(nm-connection-editor), title:(Network Connections)
windowrule = float on, match:class nm-connection-editor
windowrule = float on, match:class blueman-manager
windowrule = float on, match:class org.pulseaudio.pavucontrol
windowrule = float on, match:class org.gnome.Calendar
windowrule = size 427 600, match:class org.gnome.Calendar
#windowrule = move center, match:class org.gnome.Calendar
windowrule = move 1510 40, match:class org.gnome.Calendar
windowrule = float on, match:class org.gnome.Calculator
#windowrule = move 3424 -205, match:class org.gnome.Calendar
windowrule = float on, match:class org.gnome.Nautilus
windowrule = float on, match:class org.gnome.TextEditor
windowrule = float on, match:title Bitwarden

# windowrule = rounding 0, floating:0, onworkspace:w[tv1]
# windowrule = bordersize 0, floating:0, onworkspace:f[1]
# windowrule = rounding 0, floating:0, onworkspace:f[1]

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, match:class .*

# Fix some dragging issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0
