# Laptop multimedia keys for volume and LCD brightness
bindel = ,XF86AudioRaiseVolume, exec, $volRaise
bindel = ,XF86AudioLowerVolume, exec, $volLower
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, $brightRaise 
bindel = ,XF86MonBrightnessDown, exec, $brightLower
bindel = $mainMod ALT, up, exec, $volRaise 
bindel = $mainMod ALT, down, exec, $volLower 
bindel = $mainMod ALT, left, exec, $brightLower 
bindel = $mainMod ALT, right, exec, $brightRaise 

# Requires playerctl
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous
